//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueNorth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Answer()
        {
            this.AnswerNotes = new HashSet<AnswerNote>();
        }
    
        public int OID { get; set; }
        public Nullable<int> Question { get; set; }
        public Nullable<int> Choice { get; set; }
        public Nullable<System.Guid> User { get; set; }
        public Nullable<int> DataSet { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<int> Characteristic { get; set; }
    
        public virtual SPADataSet SPADataSet { get; set; }
        public virtual Question Question1 { get; set; }
        public virtual Characteristic Characteristic1 { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerNote> AnswerNotes { get; set; }
    }
}
