//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueNorth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacteristicGuidanceNote
    {
        public int OID { get; set; }
        public Nullable<int> Characteristic { get; set; }
        public string Text { get; set; }
        public string Markup { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual Version Version1 { get; set; }
        public virtual Characteristic Characteristic1 { get; set; }
    }
}
