//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlueForth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characteristic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Characteristic()
        {
            this.CharacteristicGuidanceNotes = new HashSet<CharacteristicGuidanceNote>();
            this.CommodityCommodities_CharacteristicCharacteristics = new HashSet<CommodityCommodities_CharacteristicCharacteristics>();
            this.SPADataSetSPADataSets_CharacteristicNonRelevantCharacteristics = new HashSet<SPADataSetSPADataSets_CharacteristicNonRelevantCharacteristics>();
            this.QuestionGroupQuestionGroups_CharacteristicCharacteristics = new HashSet<QuestionGroupQuestionGroups_CharacteristicCharacteristics>();
            this.Answers = new HashSet<Answer>();
            this.QuestionQuestions_CharacteristicCharacteristics = new HashSet<QuestionQuestions_CharacteristicCharacteristics>();
            this.FrameworkFrameworks_CharacteristicCharacteristics = new HashSet<FrameworkFrameworks_CharacteristicCharacteristics>();
            this.Scorings = new HashSet<Scoring>();
            this.StandardContentStandardContents_CharacteristicCharacteristics = new HashSet<StandardContentStandardContents_CharacteristicCharacteristics>();
            this.PriorCharacteristics = new HashSet<PriorCharacteristic>();
            this.UnitCharacteristicScores = new HashSet<UnitCharacteristicScore>();
            this.Indicators = new HashSet<Indicator>();
            this.ImprovementPlanItems = new HashSet<ImprovementPlanItem>();
        }
    
        public int OID { get; set; }
        public string Title { get; set; }
        public string ShortTitle { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public string Summary { get; set; }
        public string GuidanceText { get; set; }
        public Nullable<int> Principle { get; set; }
        public Nullable<int> PrincipleGroup { get; set; }
        public Nullable<int> CommodityCategory { get; set; }
        public Nullable<int> OrganisationType { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public string NonFulfilmentRisks { get; set; }
    
        public virtual CommodityCategory CommodityCategory1 { get; set; }
        public virtual OrganisationType OrganisationType1 { get; set; }
        public virtual PrincipleGroup PrincipleGroup1 { get; set; }
        public virtual Version Version1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacteristicGuidanceNote> CharacteristicGuidanceNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityCommodities_CharacteristicCharacteristics> CommodityCommodities_CharacteristicCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPADataSetSPADataSets_CharacteristicNonRelevantCharacteristics> SPADataSetSPADataSets_CharacteristicNonRelevantCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionGroupQuestionGroups_CharacteristicCharacteristics> QuestionGroupQuestionGroups_CharacteristicCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionQuestions_CharacteristicCharacteristics> QuestionQuestions_CharacteristicCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrameworkFrameworks_CharacteristicCharacteristics> FrameworkFrameworks_CharacteristicCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scoring> Scorings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardContentStandardContents_CharacteristicCharacteristics> StandardContentStandardContents_CharacteristicCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriorCharacteristic> PriorCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitCharacteristicScore> UnitCharacteristicScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicator> Indicators { get; set; }
        public virtual Principle Principle1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImprovementPlanItem> ImprovementPlanItems { get; set; }
    }
}
