//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueNorth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commodity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commodity()
        {
            this.CommodityCommodities_CharacteristicCharacteristics = new HashSet<CommodityCommodities_CharacteristicCharacteristics>();
            this.CommodityIndicatorGuidances = new HashSet<CommodityIndicatorGuidance>();
            this.CommodityPDValues = new HashSet<CommodityPDValue>();
            this.DimensionDimensions_CommodityCommodities = new HashSet<DimensionDimensions_CommodityCommodities>();
            this.FrameworkFrameworks_CommodityCommodities = new HashSet<FrameworkFrameworks_CommodityCommodities>();
            this.PrinciplePrinciples_CommodityCommodities = new HashSet<PrinciplePrinciples_CommodityCommodities>();
            this.Scorings = new HashSet<Scoring>();
            this.StandardStandards_CommodityCommodities = new HashSet<StandardStandards_CommodityCommodities>();
            this.SupplierSuppliers_CommodityCommodities = new HashSet<SupplierSuppliers_CommodityCommodities>();
            this.Units = new HashSet<Unit>();
            this.UnitSecondaryUnits_CommoditySecondaryCommodities = new HashSet<UnitSecondaryUnits_CommoditySecondaryCommodities>();
            this.UnitUnits_CommodityCommodities = new HashSet<UnitUnits_CommodityCommodities>();
            this.CommodityPDMValues = new HashSet<CommodityPDMValue>();
            this.PrimaryDataFieldUserEditModes = new HashSet<PrimaryDataFieldUserEditMode>();
        }
    
        public int OID { get; set; }
        public string Reference { get; set; }
        public string Title { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<int> UnitType { get; set; }
    
        public virtual CommodityCategory CommodityCategory { get; set; }
        public virtual UnitType UnitType1 { get; set; }
        public virtual Version Version1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityCommodities_CharacteristicCharacteristics> CommodityCommodities_CharacteristicCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityIndicatorGuidance> CommodityIndicatorGuidances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityPDValue> CommodityPDValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimensionDimensions_CommodityCommodities> DimensionDimensions_CommodityCommodities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrameworkFrameworks_CommodityCommodities> FrameworkFrameworks_CommodityCommodities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrinciplePrinciples_CommodityCommodities> PrinciplePrinciples_CommodityCommodities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scoring> Scorings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardStandards_CommodityCommodities> StandardStandards_CommodityCommodities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierSuppliers_CommodityCommodities> SupplierSuppliers_CommodityCommodities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit> Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitSecondaryUnits_CommoditySecondaryCommodities> UnitSecondaryUnits_CommoditySecondaryCommodities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitUnits_CommodityCommodities> UnitUnits_CommodityCommodities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityPDMValue> CommodityPDMValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryDataFieldUserEditMode> PrimaryDataFieldUserEditModes { get; set; }
    }
}
