//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlueForth.WebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlueNorthEntities : DbContext
    {
        public BlueNorthEntities()
            : base("name=BlueNorthEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<CharacteristicGuidanceNote> CharacteristicGuidanceNotes { get; set; }
        public virtual DbSet<CommodityCategory> CommodityCategories { get; set; }
        public virtual DbSet<CommodityIndicatorGuidance> CommodityIndicatorGuidances { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Dimension> Dimensions { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<PermissionPolicyUser> PermissionPolicyUsers { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PhoneNumber> PhoneNumbers { get; set; }
        public virtual DbSet<PrincipleGroup> PrincipleGroups { get; set; }
        public virtual DbSet<QuestionGroup> QuestionGroups { get; set; }
        public virtual DbSet<Retailer> Retailers { get; set; }
        public virtual DbSet<Standard> Standards { get; set; }
        public virtual DbSet<StandardChapter> StandardChapters { get; set; }
        public virtual DbSet<StandardContent> StandardContents { get; set; }
        public virtual DbSet<StandardStandards_CommodityCommodities> StandardStandards_CommodityCommodities { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierSuppliers_CommodityCommodities> SupplierSuppliers_CommodityCommodities { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }
        public virtual DbSet<UnitType> UnitTypes { get; set; }
        public virtual DbSet<Version> Versions { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<PermissionPolicyRole> PermissionPolicyRoles { get; set; }
        public virtual DbSet<PermissionPolicyUserUsers_PermissionPolicyRoleRoles> PermissionPolicyUserUsers_PermissionPolicyRoleRoles { get; set; }
        public virtual DbSet<CommodityCommodities_CharacteristicCharacteristics> CommodityCommodities_CharacteristicCharacteristics { get; set; }
        public virtual DbSet<DimensionDimensions_CommodityCommodities> DimensionDimensions_CommodityCommodities { get; set; }
        public virtual DbSet<PrinciplePrinciples_CommodityCommodities> PrinciplePrinciples_CommodityCommodities { get; set; }
        public virtual DbSet<SupplierRetailers_RetailerSuppliers> SupplierRetailers_RetailerSuppliers { get; set; }
        public virtual DbSet<UnitUnits_RetailerRetailers> UnitUnits_RetailerRetailers { get; set; }
        public virtual DbSet<UnitOfMeasureUnitsOfMeasure_PrimaryDataFieldPrimaryDataFields> UnitOfMeasureUnitsOfMeasure_PrimaryDataFieldPrimaryDataFields { get; set; }
        public virtual DbSet<PrimaryDataType> PrimaryDataTypes { get; set; }
        public virtual DbSet<OrganisationType> OrganisationTypes { get; set; }
        public virtual DbSet<SPADataSet> SPADataSets { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<IndicatorDataSet> IndicatorDataSets { get; set; }
        public virtual DbSet<Characteristic> Characteristics { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<SPADataSetSPADataSets_CharacteristicNonRelevantCharacteristics> SPADataSetSPADataSets_CharacteristicNonRelevantCharacteristics { get; set; }
        public virtual DbSet<QuestionGroupQuestionGroups_CharacteristicCharacteristics> QuestionGroupQuestionGroups_CharacteristicCharacteristics { get; set; }
        public virtual DbSet<QuestionQuestions_CharacteristicCharacteristics> QuestionQuestions_CharacteristicCharacteristics { get; set; }
        public virtual DbSet<FrameworkFrameworks_CharacteristicCharacteristics> FrameworkFrameworks_CharacteristicCharacteristics { get; set; }
        public virtual DbSet<FrameworkFrameworks_CommodityCommodities> FrameworkFrameworks_CommodityCommodities { get; set; }
        public virtual DbSet<Scoring> Scorings { get; set; }
        public virtual DbSet<StandardContentStandardContents_CharacteristicCharacteristics> StandardContentStandardContents_CharacteristicCharacteristics { get; set; }
        public virtual DbSet<UnitUnits_StandardStandards> UnitUnits_StandardStandards { get; set; }
        public virtual DbSet<Framework> Frameworks { get; set; }
        public virtual DbSet<UnitUnits_SupplierSuppliers> UnitUnits_SupplierSuppliers { get; set; }
        public virtual DbSet<PriorCharacteristic> PriorCharacteristics { get; set; }
        public virtual DbSet<StatusMatrix> StatusMatrices { get; set; }
        public virtual DbSet<PrimaryDataValue> PrimaryDataValues { get; set; }
        public virtual DbSet<IndicatorIndicators_FrameworkFrameworks> IndicatorIndicators_FrameworkFrameworks { get; set; }
        public virtual DbSet<PrimaryDataFieldPrimaryDataFields_IndicatorIndicators> PrimaryDataFieldPrimaryDataFields_IndicatorIndicators { get; set; }
        public virtual DbSet<PrimaryDataFieldNote> PrimaryDataFieldNotes { get; set; }
        public virtual DbSet<ProductionArea> ProductionAreas { get; set; }
        public virtual DbSet<UnitUnits_CommodityCommodities> UnitUnits_CommodityCommodities { get; set; }
        public virtual DbSet<UserUsers_IndicatorIndicators> UserUsers_IndicatorIndicators { get; set; }
        public virtual DbSet<PrimaryDataField> PrimaryDataFields { get; set; }
        public virtual DbSet<CommodityPDValue> CommodityPDValues { get; set; }
        public virtual DbSet<DataFieldCategory> DataFieldCategories { get; set; }
        public virtual DbSet<StandardContentStandardContents_QuestionGroupQuestionGroups> StandardContentStandardContents_QuestionGroupQuestionGroups { get; set; }
        public virtual DbSet<IndicatorIndicators_ConversionFactorConversionFactors> IndicatorIndicators_ConversionFactorConversionFactors { get; set; }
        public virtual DbSet<XPObjectType> XPObjectTypes { get; set; }
        public virtual DbSet<UnitCharacteristicScore> UnitCharacteristicScores { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<FileData> FileDatas { get; set; }
        public virtual DbSet<PrimaryDataFieldUserEditMode> PrimaryDataFieldUserEditModes { get; set; }
        public virtual DbSet<StandardContentStandardContents_ImprovementPlanItemImprovementPlanItems> StandardContentStandardContents_ImprovementPlanItemImprovementPlanItems { get; set; }
        public virtual DbSet<UserAssignedForUsers_UnitAssignedUnits> UserAssignedForUsers_UnitAssignedUnits { get; set; }
        public virtual DbSet<UserCreatedByUsers_UnitCreatedUnits> UserCreatedByUsers_UnitCreatedUnits { get; set; }
        public virtual DbSet<AnswerNote> AnswerNotes { get; set; }
        public virtual DbSet<AnswerNoteAttachment> AnswerNoteAttachments { get; set; }
        public virtual DbSet<ConversionFactor> ConversionFactors { get; set; }
        public virtual DbSet<Indicator> Indicators { get; set; }
        public virtual DbSet<Principle> Principles { get; set; }
        public virtual DbSet<UnitSecondaryUnits_CommoditySecondaryCommodities> UnitSecondaryUnits_CommoditySecondaryCommodities { get; set; }
        public virtual DbSet<ImprovementPlanItem> ImprovementPlanItems { get; set; }
        public virtual DbSet<FrameworkFrontMenuItem> FrameworkFrontMenuItems { get; set; }
        public virtual DbSet<FrontMenuItem> FrontMenuItems { get; set; }
        public virtual DbSet<PrimaryDataMonthValue> PrimaryDataMonthValues { get; set; }
        public virtual DbSet<Commodity> Commodities { get; set; }
        public virtual DbSet<CommodityPDMValue> CommodityPDMValues { get; set; }
    }
}
