//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueNorth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Framework
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Framework()
        {
            this.FrameworkFrameworks_CharacteristicCharacteristics = new HashSet<FrameworkFrameworks_CharacteristicCharacteristics>();
            this.FrameworkFrameworks_CommodityCommodities = new HashSet<FrameworkFrameworks_CommodityCommodities>();
            this.Units = new HashSet<Unit>();
            this.IndicatorDataSets = new HashSet<IndicatorDataSet>();
            this.SPADataSets = new HashSet<SPADataSet>();
            this.IndicatorIndicators_FrameworkFrameworks = new HashSet<IndicatorIndicators_FrameworkFrameworks>();
            this.UnitCharacteristicScores = new HashSet<UnitCharacteristicScore>();
            this.FrameworkFrontMenuItems = new HashSet<FrameworkFrontMenuItem>();
        }
    
        public int OID { get; set; }
        public string Title { get; set; }
        public string ShortTitle { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<int> OrganisationType { get; set; }
        public Nullable<int> ScoringMode { get; set; }
    
        public virtual OrganisationType OrganisationType1 { get; set; }
        public virtual Version Version1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrameworkFrameworks_CharacteristicCharacteristics> FrameworkFrameworks_CharacteristicCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrameworkFrameworks_CommodityCommodities> FrameworkFrameworks_CommodityCommodities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit> Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicatorDataSet> IndicatorDataSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPADataSet> SPADataSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicatorIndicators_FrameworkFrameworks> IndicatorIndicators_FrameworkFrameworks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitCharacteristicScore> UnitCharacteristicScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrameworkFrontMenuItem> FrameworkFrontMenuItems { get; set; }
    }
}
