//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlueForth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrameworkFrontMenuItem
    {
        public int OID { get; set; }
        public Nullable<int> Framework { get; set; }
        public Nullable<int> FrontMenuItem { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual Framework Framework1 { get; set; }
        public virtual FrontMenuItem FrontMenuItem1 { get; set; }
    }
}
