//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlueForth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImprovementPlanItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImprovementPlanItem()
        {
            this.StandardContentStandardContents_ImprovementPlanItemImprovementPlanItems = new HashSet<StandardContentStandardContents_ImprovementPlanItemImprovementPlanItems>();
        }
    
        public int OID { get; set; }
        public Nullable<int> DataSet { get; set; }
        public Nullable<int> Characteristic { get; set; }
        public Nullable<int> Question { get; set; }
        public string Actions { get; set; }
        public string Resposible { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Result { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<int> StandardContent { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<System.Guid> Attachment { get; set; }
    
        public virtual Characteristic Characteristic1 { get; set; }
        public virtual FileData FileData { get; set; }
        public virtual SPADataSet SPADataSet { get; set; }
        public virtual Question Question1 { get; set; }
        public virtual StandardContent StandardContent1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardContentStandardContents_ImprovementPlanItemImprovementPlanItems> StandardContentStandardContents_ImprovementPlanItemImprovementPlanItems { get; set; }
    }
}
