//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueNorth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indicator()
        {
            this.CommodityIndicatorGuidances = new HashSet<CommodityIndicatorGuidance>();
            this.IndicatorIndicators_ConversionFactorConversionFactors = new HashSet<IndicatorIndicators_ConversionFactorConversionFactors>();
            this.IndicatorIndicators_FrameworkFrameworks = new HashSet<IndicatorIndicators_FrameworkFrameworks>();
            this.PrimaryDataFieldPrimaryDataFields_IndicatorIndicators = new HashSet<PrimaryDataFieldPrimaryDataFields_IndicatorIndicators>();
            this.UserUsers_IndicatorIndicators = new HashSet<UserUsers_IndicatorIndicators>();
        }
    
        public int OID { get; set; }
        public string Title { get; set; }
        public string ShortTitle { get; set; }
        public Nullable<int> Characteristic { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public string Markup { get; set; }
        public string Formula { get; set; }
        public Nullable<int> Order { get; set; }
        public string Guidance { get; set; }
        public string Interpretaion { get; set; }
        public string Relevance { get; set; }
        public Nullable<int> UnitOfMeasure { get; set; }
        public Nullable<int> Conversion { get; set; }
        public Nullable<decimal> TresholdValue { get; set; }
    
        public virtual Characteristic Characteristic1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityIndicatorGuidance> CommodityIndicatorGuidances { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure1 { get; set; }
        public virtual Version Version1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicatorIndicators_ConversionFactorConversionFactors> IndicatorIndicators_ConversionFactorConversionFactors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicatorIndicators_FrameworkFrameworks> IndicatorIndicators_FrameworkFrameworks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryDataFieldPrimaryDataFields_IndicatorIndicators> PrimaryDataFieldPrimaryDataFields_IndicatorIndicators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserUsers_IndicatorIndicators> UserUsers_IndicatorIndicators { get; set; }
    }
}
