//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueNorth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryDataFieldUserEditMode
    {
        public int OID { get; set; }
        public Nullable<int> PrimaryDataField { get; set; }
        public Nullable<System.Guid> User { get; set; }
        public Nullable<int> AreaSizeMode { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<int> PeriodDataMode { get; set; }
        public Nullable<int> Commodity { get; set; }
    
        public virtual PrimaryDataField PrimaryDataField1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual Commodity Commodity1 { get; set; }
    }
}
