//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueNorth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryDataField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrimaryDataField()
        {
            this.PrimaryDataField1 = new HashSet<PrimaryDataField>();
            this.PrimaryDataFieldNotes = new HashSet<PrimaryDataFieldNote>();
            this.PrimaryDataFieldPrimaryDataFields_IndicatorIndicators = new HashSet<PrimaryDataFieldPrimaryDataFields_IndicatorIndicators>();
            this.PrimaryDataValues = new HashSet<PrimaryDataValue>();
            this.UnitOfMeasureUnitsOfMeasure_PrimaryDataFieldPrimaryDataFields = new HashSet<UnitOfMeasureUnitsOfMeasure_PrimaryDataFieldPrimaryDataFields>();
            this.PrimaryDataFieldUserEditModes = new HashSet<PrimaryDataFieldUserEditMode>();
        }
    
        public int OID { get; set; }
        public Nullable<int> PrimaryDataType { get; set; }
        public string GuidanceNotes { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<int> DefaultUOM { get; set; }
        public string Reference { get; set; }
        public string Name { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<int> DependendOn { get; set; }
        public Nullable<bool> IsCommodityDependendent { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> IsMonthlyDataModeAvailable { get; set; }
    
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryDataField> PrimaryDataField1 { get; set; }
        public virtual PrimaryDataField PrimaryDataField2 { get; set; }
        public virtual PrimaryDataType PrimaryDataType1 { get; set; }
        public virtual Version Version1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryDataFieldNote> PrimaryDataFieldNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryDataFieldPrimaryDataFields_IndicatorIndicators> PrimaryDataFieldPrimaryDataFields_IndicatorIndicators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryDataValue> PrimaryDataValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitOfMeasureUnitsOfMeasure_PrimaryDataFieldPrimaryDataFields> UnitOfMeasureUnitsOfMeasure_PrimaryDataFieldPrimaryDataFields { get; set; }
        public virtual DataFieldCategory DataFieldCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryDataFieldUserEditMode> PrimaryDataFieldUserEditModes { get; set; }
    }
}
