//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlueForth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryDataFieldNote
    {
        public int OID { get; set; }
        public Nullable<int> PrimaryDataField { get; set; }
        public Nullable<int> DataSet { get; set; }
        public Nullable<System.Guid> User { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual IndicatorDataSet IndicatorDataSet { get; set; }
        public virtual PrimaryDataField PrimaryDataField1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
