//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueNorth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scoring
    {
        public int OID { get; set; }
        public Nullable<int> Characteristic { get; set; }
        public Nullable<int> Commodity { get; set; }
        public Nullable<int> UnitType { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual Characteristic Characteristic1 { get; set; }
        public virtual Commodity Commodity1 { get; set; }
        public virtual UnitType UnitType1 { get; set; }
    }
}
