//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlueForth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPADataSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPADataSet()
        {
            this.Answers = new HashSet<Answer>();
            this.SPADataSetSPADataSets_CharacteristicNonRelevantCharacteristics = new HashSet<SPADataSetSPADataSets_CharacteristicNonRelevantCharacteristics>();
            this.PriorCharacteristics = new HashSet<PriorCharacteristic>();
            this.ImprovementPlanItems = new HashSet<ImprovementPlanItem>();
        }
    
        public int OID { get; set; }
        public Nullable<System.Guid> Unit { get; set; }
        public Nullable<int> AssessmentType { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<int> Framework { get; set; }
    
        public virtual Grade Grade1 { get; set; }
        public virtual Unit Unit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPADataSetSPADataSets_CharacteristicNonRelevantCharacteristics> SPADataSetSPADataSets_CharacteristicNonRelevantCharacteristics { get; set; }
        public virtual Framework Framework1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriorCharacteristic> PriorCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImprovementPlanItem> ImprovementPlanItems { get; set; }
    }
}
