//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueNorth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StandardContent()
        {
            this.StandardContentStandardContents_CharacteristicCharacteristics = new HashSet<StandardContentStandardContents_CharacteristicCharacteristics>();
            this.StandardContentStandardContents_QuestionGroupQuestionGroups = new HashSet<StandardContentStandardContents_QuestionGroupQuestionGroups>();
            this.StandardContentStandardContents_ImprovementPlanItemImprovementPlanItems = new HashSet<StandardContentStandardContents_ImprovementPlanItemImprovementPlanItems>();
            this.ImprovementPlanItems = new HashSet<ImprovementPlanItem>();
        }
    
        public int OID { get; set; }
        public string Title { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public Nullable<int> StandardChapter { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual StandardChapter StandardChapter1 { get; set; }
        public virtual Version Version1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardContentStandardContents_CharacteristicCharacteristics> StandardContentStandardContents_CharacteristicCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardContentStandardContents_QuestionGroupQuestionGroups> StandardContentStandardContents_QuestionGroupQuestionGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardContentStandardContents_ImprovementPlanItemImprovementPlanItems> StandardContentStandardContents_ImprovementPlanItemImprovementPlanItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImprovementPlanItem> ImprovementPlanItems { get; set; }
    }
}
