//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlueForth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusMatrix
    {
        public int OID { get; set; }
        public string Code { get; set; }
        public Nullable<int> Zone { get; set; }
        public string Reference { get; set; }
        public Nullable<double> AdjScore { get; set; }
        public string StatusText { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    }
}
