//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueNorth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitCharacteristicScore
    {
        public int OID { get; set; }
        public Nullable<int> Characteristic { get; set; }
        public Nullable<int> Framework { get; set; }
        public Nullable<System.Guid> Unit { get; set; }
        public Nullable<System.DateTime> Calculated { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual Characteristic Characteristic1 { get; set; }
        public virtual Framework Framework1 { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
