//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueNorth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnitOfMeasure()
        {
            this.UnitOfMeasureUnitsOfMeasure_PrimaryDataFieldPrimaryDataFields = new HashSet<UnitOfMeasureUnitsOfMeasure_PrimaryDataFieldPrimaryDataFields>();
            this.PrimaryDataFields = new HashSet<PrimaryDataField>();
            this.ConversionFactors = new HashSet<ConversionFactor>();
            this.ConversionFactors1 = new HashSet<ConversionFactor>();
            this.Indicators = new HashSet<Indicator>();
        }
    
        public int OID { get; set; }
        public string Title { get; set; }
        public string ShortTitle { get; set; }
        public string Symbol { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual Version Version1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitOfMeasureUnitsOfMeasure_PrimaryDataFieldPrimaryDataFields> UnitOfMeasureUnitsOfMeasure_PrimaryDataFieldPrimaryDataFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryDataField> PrimaryDataFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConversionFactor> ConversionFactors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConversionFactor> ConversionFactors1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicator> Indicators { get; set; }
    }
}
