//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueNorth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Answers = new HashSet<Answer>();
            this.PrimaryDataFieldNotes = new HashSet<PrimaryDataFieldNote>();
            this.UserUsers_IndicatorIndicators = new HashSet<UserUsers_IndicatorIndicators>();
            this.Versions = new HashSet<Version>();
            this.Versions1 = new HashSet<Version>();
            this.PrimaryDataFieldUserEditModes = new HashSet<PrimaryDataFieldUserEditMode>();
            this.UserAssignedForUsers_UnitAssignedUnits = new HashSet<UserAssignedForUsers_UnitAssignedUnits>();
            this.UserCreatedByUsers_UnitCreatedUnits = new HashSet<UserCreatedByUsers_UnitCreatedUnits>();
        }
    
        public System.Guid Oid { get; set; }
        public Nullable<System.Guid> Person { get; set; }
        public Nullable<System.Guid> Organisation { get; set; }
        public Nullable<System.Guid> CurrentUnit { get; set; }
        public Nullable<bool> AcceptedTermsConditions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Organisation Organisation1 { get; set; }
        public virtual PermissionPolicyUser PermissionPolicyUser { get; set; }
        public virtual Person Person1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryDataFieldNote> PrimaryDataFieldNotes { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserUsers_IndicatorIndicators> UserUsers_IndicatorIndicators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Version> Versions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Version> Versions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryDataFieldUserEditMode> PrimaryDataFieldUserEditModes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAssignedForUsers_UnitAssignedUnits> UserAssignedForUsers_UnitAssignedUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCreatedByUsers_UnitCreatedUnits> UserCreatedByUsers_UnitCreatedUnits { get; set; }
    }
}
