//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlueForth.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCreatedByUsers_UnitCreatedUnits
    {
        public Nullable<System.Guid> CreatedUnits { get; set; }
        public Nullable<System.Guid> CreatedByUsers { get; set; }
        public System.Guid OID { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual User User { get; set; }
    }
}
